name: Deploy Vercel

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NX_VERCEL_REMOTE_CACHE_TOKEN: ${{secrets.VERCEL_TOKEN}}
  NX_VERCEL_REMOTE_CACHE_TEAM: ${{secrets.VERCEL_ORG_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile --ignore-scripts

      - run: bunx nx run-many -t build

      - run: bunx vercel@latest pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}
      - run: bunx vercel@latest build --token=${{secrets.VERCEL_TOKEN}}
      - run: bunx vercel@latest deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}}
